ATARI_100K_GAMES = [
    "Alien",
    "Amidar",
    "Assault",
    "Asterix",
    "BankHeist",
    "BattleZone",
    "Boxing",
    "Breakout",
    "ChopperCommand",
    "CrazyClimber",
    "DemonAttack",
    "Freeway",
    "Frostbite",
    "Gopher",
    "Hero",
    "Jamesbond",
    "Kangaroo",
    "Krull",
    "KungFuMaster",
    "MsPacman",
    "Pong",
    "PrivateEye",
    "Qbert",
    "RoadRunner",
    "Seaquest",
    "UpNDown",
]

GAMES_REWARD_LB = {
    "Amidar": 0,
    "Asterix": 0,
    "Boxing": -1,
    "Breakout": 0,
    "ChopperCommand": 0,
    "Gopher": 0,
    "KungFuMaster": 0,
    "MsPacman": 0,
    "Pong": -1,
    "Qbert": 0,
    "RoadRunner": 0,
    "Seaquest": 0,
}